# Generated by Django 3.2.6 on 2021-08-21 19:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id_produto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_produto', models.IntegerField()),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('categoria', models.CharField(max_length=255)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
