# Generated by Django 3.2.6 on 2021-12-14 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='id_produto',
            new_name='id',
        ),
    ]
