# Generated by Django 3.2.6 on 2021-09-21 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicos',
            old_name='funcao',
            new_name='cliente_id',
        ),
        migrations.RenameField(
            model_name='servicos',
            old_name='is_admin',
            new_name='servico_realizado',
        ),
        migrations.RenameField(
            model_name='servicos',
            old_name='login',
            new_name='veiculo',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='sobrenome',
        ),
    ]
