# Generated by Django 3.2.6 on 2021-12-15 03:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('contato', models.CharField(max_length=255)),
                ('veiculo', models.CharField(max_length=255)),
            ],
        ),
    ]
